import numpy as np

# List of baseball-specific questions
questions = [
"Have you found yourself feeling more tired than usual, even after a good night's sleep?",
"Do you find it harder to get going in the mornings lately?",
"Have you been skipping meals or eating more irregularly than usual?",
"Do you find yourself reaching for more sugary or unhealthy snacks lately?",
"Have you noticed any changes in your usual workout routine or motivation to train?",
"Do you feel like you're going through the motions during practice without real focus?",
"Have you found yourself making more careless mistakes lately?",
"Do you feel like your reactions are a bit slower than they used to be?",
"Have you been having difficulty making quick decisions on the field?",
"Do you find it hard to switch off and relax when you're away from the ballpark?",
"Have you been spending more time alone lately than you typically do?",
"Do you find yourself less interested in hanging out with teammates off the field?",
"Have you been avoiding certain social situations or team events?",
"Do you find it harder to engage in casual conversations with teammates?",
"Have you been keeping to yourself more during team travel?",
"Do you find yourself feeling more easily frustrated by small things?",
"Have you had a shorter temper than usual with teammates or coaches?",
"Do you find yourself getting annoyed by things that normally wouldn't bother you?",
"Have you been more critical of your own performance lately?",
"Do you find it hard to accept positive feedback or praise?",
"Have you been dwelling on minor mistakes or imperfections in your game?",
"Do you feel like you're underperforming compared to your potential?",
"Have you been setting very high expectations for yourself in every game?",
"Do you feel a lot of pressure to prove yourself constantly?",
"Have you been worried about what others think of your performance?",
"Do you find yourself replaying negative scenarios in your head?",
"Have you been having trouble falling asleep at night?",
"Do you often wake up in the middle of the night and struggle to fall back asleep?",
"Do you feel restless or uneasy when you try to relax?",
"Have you been having vivid or disturbing dreams lately?",
"Do you find yourself worrying about upcoming games or practices days in advance?",
"Have you been checking stats or social media about your performance more often than usual?",
"Do you feel a need to constantly monitor your progress and compare it to others?",
"Have you been seeking reassurance about your abilities from others?",
"Do you find it hard to trust your instincts on the field lately?",
"Have you been second-guessing your decisions during games?",
"Do you feel less confident in your skills and abilities than you used to?",
"Have you been avoiding challenging situations on the field?",
"Do you find yourself hesitant to take risks or make aggressive plays?",
"Have you been focusing more on avoiding mistakes than on making positive plays?",
"Do you feel like you're playing it safe rather than playing your best?",
"Have you been less vocal or assertive during games?",
"Do you find it harder to communicate effectively with your teammates on the field?",
"Have you been hesitant to share your opinions or ideas with the team?",
"Do you feel like your voice isn't being heard or valued?",
"Have you been more sensitive to criticism or feedback lately?",
"Do you find yourself getting defensive when your performance is discussed?",
"Have you been avoiding conversations about your game with coaches or teammates?",
"Do you feel like you have to constantly defend your decisions or actions?",
"Have you been experiencing any muscle tension or headaches more frequently?",
"Do you notice your heart racing or feeling palpitations sometimes?",
"Have you had any stomach issues or digestive problems lately?",
"Do you find yourself clenching your jaw or grinding your teeth?",
"Have you been feeling more physically fatigued than usual?",
"Do you find it harder to recover after games or workouts?",
"Have you been neglecting your usual self-care routines?",
"Do you find it harder to motivate yourself to do things you know are good for you?",
"Have you been less patient with yourself and others?",
"Do you find yourself getting easily irritated by minor inconveniences?",
"Have you been feeling a sense of unease or restlessness?",
"Do you find it hard to sit still or relax?",
"Have you been avoiding eye contact with people more often?",
"Do you feel like you're going through the motions without really feeling present?",
"Have you lost some of the joy and excitement you used to feel for baseball?",
"Do you find yourself questioning whether you still want to play?",
"Have you been thinking about what else you might do if you weren't playing baseball?",
"Do you feel like you're carrying a heavy burden lately?",
"Have you been having difficulty concentrating on tasks outside of baseball?",
"Do you find yourself easily distracted by your thoughts?",
"Have you been more indecisive than usual?",
"Do you feel less in control of your emotions than you used to?",
"Have you had moments where you felt a surge of anger or frustration?",
"Do you find yourself feeling sad or down for no apparent reason?",
"Have you had moments where you felt a sense of emptiness or numbness?",
"Do you feel like you're going through a period of significant change or uncertainty?",
"Have you been experiencing any major life events or transitions recently?",
"Do you feel like you have a strong support system to help you through tough times?",
"Have you been hesitant to reach out to your support network for help?",
"Do you feel like you need to handle everything on your own?",
"Have you been putting pressure on yourself to be strong and independent?",
"Do you believe that showing vulnerability is a sign of weakness?",
"Have you been trying to suppress or ignore difficult emotions?",
"Do you find yourself using humor or sarcasm to deflect from serious conversations?",
"Have you been minimizing your problems or telling yourself they're not a big deal?",
"Do you feel like you have to maintain a perfect image to the outside world?",
"Have you been feeling unusually irritable or on edge lately?",
"Are you finding it harder to enjoy activities you used to love?",
"Have you experienced any significant changes in your appetite or weight recently?",
"Do you often feel overwhelmed by the demands of your baseball career?",
"Have you noticed a decrease in your motivation or energy levels?",
"Are you worried about your future in baseball?",
"Do you feel like you're carrying the weight of the team's performance on your shoulders?",
"Have you been comparing yourself unfavorably to other players?",
"Do you feel like you're not good enough, despite your efforts?",
"Are you preoccupied with past mistakes you've made in games?",
"Have you been replaying negative moments in your head repeatedly?",
"Do you find it difficult to concentrate or stay focused during practices or games?",
"Have you been more forgetful than usual?",
"Are you feeling detached or disconnected from your surroundings?",
"Do you feel a sense of hopelessness about your baseball career?",
"Have you had thoughts that life isn't worth living?",
"Do you feel like you have no one to talk to about your struggles?",
"Have you been hesitant to ask for help because you don't want to appear weak?",
"Are you worried about the stigma associated with mental health issues in baseball?",
"Do you believe that mental toughness means never showing vulnerability?",
"Have you been relying on caffeine or other stimulants to get through the day?",
"Do you find yourself worrying excessively about things that might happen?",
"Are you experiencing racing thoughts that you can't seem to control?",
"Have you had panic attacks or sudden feelings of intense fear?",
"Does the thought of upcoming games fill you with dread?",
"Are you constantly seeking reassurance from others about your performance?",
"Do you feel the need to be perfect in every aspect of your game?",
"Have you set unrealistically high standards for yourself?",
"Are you afraid of failing to meet the expectations of your coaches or fans?",
"Do you believe that your worth as a person is tied to your performance on the field?",
"Have you been pulling away from your usual social activities?",
"Do you feel more comfortable being alone than with your teammates?",
"Have you noticed a strain in your relationships with your family or friends?",
"Are you finding it difficult to be present in conversations?",
"Have you been using social media excessively as an escape?",
"Do you feel like you're putting on a brave face, but inside you're struggling?",
"Have you been avoiding situations that remind you of your performance struggles?",
"Do you find it difficult to relax or unwind after games?",
"Are you taking your frustrations out on others?",
"Have you been having more arguments or disagreements than usual?",
"Do you feel like you're walking on eggshells around certain people?",
"Have you been using food for comfort or to cope with stress?",
"Are you neglecting your physical health due to your mental state?",
"Have you stopped doing things that usually bring you joy or relaxation?",
"Do you feel like you're just going through the motions?",
"Have you lost interest in watching or following baseball outside of your own games?",
"Are you feeling burnt out from the constant demands of the sport?",
"Have you been struggling to make decisions, even small ones?",
"Do you feel a sense of brain fog or mental cloudiness?",
"Have you noticed any changes in your reaction time or coordination?",
"Are you concerned about the impact of your mental state on your physical health?",
"Have you tried any over-the-counter remedies for sleep or anxiety?",
"Do you feel like you're constantly fighting an uphill battle?",
"Have you been questioning your love for the game of baseball?",
"Do you feel a sense of grief or loss related to your performance struggles?",
"Have you been experiencing any unusual physical aches or pains?",
"Are you worried about the financial implications of not performing well?",
"Do you feel pressure to maintain a certain image or persona?",
"Have you been actively trying to hide your struggles from others?",
"Do you feel like you're living a double life, one on and one off the field?",
"Have you been using humor or sarcasm to deflect from your true feelings?",
"Do you find yourself being overly critical of yourself or others?",
"Have you noticed a change in your ability to handle feedback or criticism?",
"Are you feeling resentful towards teammates who are performing well?",
"Do you feel like you're carrying past traumas or unresolved issues with you?",
"Have you experienced any significant personal losses or challenges recently?",
"Are you worried about the impact of your mental state on your relationships outside of baseball?",
"Do you feel like you're losing control of your emotions?",
"Have you had moments where you felt completely numb or emotionless?",
"Are you concerned about the long-term impact of stress on your health?",
"Have you been avoiding situations where you might be judged or evaluated?",
"Do you feel like you're on a constant roller coaster of emotions?",
"Have you noticed any changes in your sex drive or intimacy with your partner?",
"Are you worried about the potential for career-ending injuries?",
"Do you feel like you have a strong support system outside of baseball?",
"Have you felt moments of intense anger or rage related to your performance?",
"Are you concerned about the impact of social media on your mental well-being?",
"Do you believe seeking help for mental health is a sign of weakness?",
"Have you ever felt like you were having a heart attack or other serious medical event due to anxiety?",
"Are you worried about letting down fans or the community?",
"Do you feel like you have a clear understanding of your values and purpose beyond baseball?",
"Have you been neglecting your hobbies or interests outside of the sport?",
"Do you feel like you have a healthy work-life balance?",
"Are you satisfied with the level of communication and support from your organization regarding mental health?",
"Do you feel hopeful about the future?",
"Have you been actively practicing gratitude or focusing on positive aspects of your life?",
"Do you believe you have the resources and skills to cope with the challenges you're facing?",
]

# Convert the list to a numpy array
questions_array = np.array(questions)

def get_random_close_questions():
    return np.random.choice(questions_array, 5, replace=False)