import numpy as np

# List of questions
questions = [
     "What rituals or habits help you channel nervous energy into focused performance?",
    "How do you mentally prepare for unpredictable situations during the game?",
    "What strategies do you use to stay positive when doubt or anxiety creeps in before a game?",
    "Do you visualize specific plays or outcomes before a game? How does this affect your confidence?",
    "How do you mentally prepare for games where the stakes are particularly high?",
    "When things are going exceptionally well during a game, how do you keep your momentum without getting overconfident?",
    "What’s your mental approach to facing an opponent you’ve struggled against in the past?",
    "How do you tune out external pressures, like crowd noise or opposing team distractions, during a game?",
    "What is your go-to thought or mantra when the game is on the line?",
    "How do you ensure that you stay present and not dwell on the last play, whether it was good or bad?",
    "What’s your process for celebrating small wins in your performance, even during a tough loss?",
    "How do you analyze your performance objectively without being too critical of yourself?",
    "When reviewing game footage, what mental habits help you translate observations into actionable improvements?",
    "What’s one thing you consistently do after games to decompress and reset mentally?",
    "How do you balance being proud of your progress while still striving for improvement?",
    "How do you adapt your communication style to better connect with different teammates?",
    "What’s one way you help foster a mentally strong and supportive team culture?",
    "How do you encourage teammates to keep their morale high during tough stretches of the season?",
    "When conflicts arise within the team, how do you ensure your actions contribute to a resolution?",
    "What’s the most valuable piece of advice you’ve received from a teammate about the mental side of the game?",
    "How do you balance the mental demands of baseball with other aspects of your life?",
    "What practices or hobbies outside of baseball contribute to your mental health?",
    "How do you approach managing burnout during a long season?",
    "What drives your motivation when external rewards, like recognition or wins, are lacking?",
    "What personal qualities or values do you draw upon to navigate challenges in your baseball journey?",
    "Can you describe a moment when you overcame significant mental adversity during a game? What did you learn from it?",
    "How do you rebuild your confidence after a particularly tough performance?",
    "What’s the most important lesson you’ve learned about handling failure?",
    "How do you maintain mental toughness when you’re recovering from an injury?",
    "When faced with a slump or losing streak, what steps do you take to regain your rhythm?",
    "What’s your process for setting short-term and long-term goals in baseball?",
    "How do you mentally rehearse success, and how does that translate to your physical performance?",
    "What’s one big milestone you’re working toward this season, and how do you stay focused on it daily?",
    "How do you evaluate your progress toward goals during the season?",
    "What role does self-reflection play in setting and achieving your goals?",
    "What do you do to take care of your mental health on a daily basis?",
    "When you feel overwhelmed, what’s your go-to coping mechanism?",
    "What’s one habit you’ve developed that has positively impacted your mental well-being?",
    "How do you recognize when you need a break, and what does taking a break look like for you?",
    "What does self-care mean to you, and how do you incorporate it into your life?",
    "How do you handle feelings of loneliness or isolation?",
    "What’s the most effective way you’ve found to manage stress?",
    "What does your internal dialogue sound like when you’re struggling?",
    "What’s a small thing that always brightens your day, no matter what?",
    "How do you practice gratitude, and how does it affect your mood?",
    "What is one personal goal you’re actively working on, and why is it important to you?",
    "What does success mean to you, and how do you measure it?",
    "What’s a fear you’ve overcome, and how did you do it?",
    "What motivates you to keep moving forward on difficult days?",
    "What’s one life lesson you’ve learned recently?",
    "What do you wish you could tell your past self 5 years ago?",
    "What’s one skill you’d love to learn and why?",
    "What’s your proudest personal achievement so far?",
    "What drives your passion for what you do?",
    "How do you balance ambition with self-compassion?",
    "What’s the most important quality you look for in a friend?",
    "How do you show people you care about them?",
    "What’s one way you’ve supported someone you care about recently?",
    "What does a healthy relationship mean to you?",
    "How do you communicate your feelings to others effectively?",
    "What’s one piece of advice you’d give someone struggling with a relationship issue?",
    "When was the last time you felt deeply connected to someone, and what made it special?",
    "How do you repair relationships when conflict arises?",
    "What’s a lesson about love or friendship you’ve learned the hard way?",
    "What makes you feel most valued in your relationships?",
    "What’s the hardest decision you’ve had to make, and what did you learn from it?",
    "How do you weigh the pros and cons of a tough choice?",
    "When was the last time you took a risk, and how did it turn out?",
    "What’s your approach to bouncing back after failure?",
    "How do you know when it’s time to let go of something or someone?",
    "What’s a mistake you made that turned out to be a valuable learning experience?",
    "How do you handle uncertainty in your life?",
    "What’s your strategy for staying calm under pressure?",
    "What’s a challenge you’ve overcome that changed your perspective?",
    "How do you keep going when you feel like giving up?",
    "What’s one small thing you look forward to every day?",
    "What’s a simple pleasure you never take for granted?",
    "How do you spend your ideal weekend?",
    "What’s your favorite way to unwind after a long day?",
    "What’s one thing you’ve done recently that made you smile?",
    "What’s your favorite memory from the past month?",
    "What’s the best compliment you’ve received, and why did it mean so much?",
    "What’s a tradition or routine that brings you comfort?",
    "What’s a place you go to feel at peace?",
    "What’s your favorite way to celebrate small wins?",
    "If you could pinpoint one recurring negative thought that creeps into your mind during a game, what would it be, and how are you actively working to silence it?",
    "Describe a moment where your mental game single-handedly won or lost a game for you. What did you learn from that experience about your own mental strength or weakness?",
    "What's the biggest fear you have on the baseball field, and how do you train your mind to play through it?",
    "If you could have a conversation with your self-doubts right now, what would you say to them?",
    "What's the difference between being confident and being arrogant on the field, and how do you ensure you stay on the right side of that line?",
    "Think about a teammate who consistently performs well under pressure. What specific mental attributes do they possess that you admire and are trying to emulate?",
    "What's the toughest piece of criticism you've ever received, and how did you choose to internalize or reject it to fuel your improvement?",
    "Describe a time you felt completely 'out of it' mentally during a game. What were the contributing factors, and what strategies do you have in place to prevent that from happening again?",
    "What's the one thing you believe about your abilities that nobody else sees or understands yet?",
    "If you could rewrite a past failure in your baseball career, focusing solely on your mental approach, what would you change?",
    "What's the most significant mental sacrifice you've had to make to pursue your baseball dreams?",
    "How do you personally define 'mental toughness' in a way that resonates deeply with you as a player?",
    "What's the biggest mental obstacle you've had to overcome in your journey as a baseball player, and what did that process teach you about yourself?",
    "If your mental game had a coach, what would that coach tell you are your biggest strengths and weaknesses?",
    "What's the one area of your mental game where you feel you have the most untapped potential?",
    "Describe a moment where you had to make a split-second decision under immense pressure. What mental processes allowed you to make the right choice?",
    "What's the internal battle you face most often during a game, and what mental tools do you use to win that battle?",
    "If you could instill one mental skill in every player on this team, what would it be and why?",
    "What's the most challenging aspect of maintaining a positive mental attitude when you're facing personal struggles off the field?",
    "How do you prevent the fear of failure from paralyzing your performance in crucial moments?",
    "What's the biggest mental challenge of playing on the road in a hostile environment, and how do you prepare for that?",
    "Describe a time when you had to dig deep mentally to overcome a physical challenge or injury?",
    "What's the mental edge that you believe separates good players from great players?",
    "If you could have the mental fortitude of any baseball legend, whose would it be and why?",
    "What's the most effective way your coaches or teammates can support you when you're struggling mentally?",
    "How do you personally hold yourself accountable for your mental preparation and performance?",
    "What's the one mental skill you believe is most underrated in baseball?",
    "Describe a time when you surprised yourself with your own mental toughness?",
    "What's the biggest misconception people have about the mental side of baseball?",
    "How do you handle the mental letdown after a big win or a devastating loss?",
    "What's the mental 'fuel' that keeps you going when you're feeling physically and emotionally drained?",
    "If you could give one piece of advice to your younger self about the mental game, knowing what you know now, what would it be?",
    "What's the mental 'fire' that drives your competitive spirit?",
    "How do you bounce back mentally from a bad call by an umpire?",
    "What's your mental strategy for staying calm and focused when facing a pitcher with exceptional velocity or movement?",
    "Describe a time when you had to mentally take charge and influence the outcome of a game?",
    "What's the biggest mental adjustment you've had to make as you've progressed through different levels of baseball?",
    "How do you use your pre-game routine to mentally 'flip the switch' and get into game mode?",
    "What's the mental aspect of baseball that you find the most fascinating or intriguing?",
    "How do you prevent negative external influences (e.g., social media, critical fans) from affecting your mental state?",
    "What's the mental image you have in your mind when you're performing at your absolute best?",
    "How do you mentally prepare for playing in unpredictable weather conditions?",
    "What's the mental cost of dwelling on past mistakes, and how do you actively choose to move forward?",
    "Describe a time when you had to make a difficult decision that went against your instincts, but was the right mental play for the team?",
    "What's the mental 'anchor' that keeps you grounded and focused during the ups and downs of a season?",
    "How do you cultivate a sense of mental resilience within the team as a whole?",
    "What's the mental legacy you hope to leave behind as a baseball player?",
    "If you could ask any mental performance expert one question, what would it be?",
    "What's the most significant mental breakthrough you've experienced in your baseball career?",
    "How do you train your mind to stay aggressive and assertive, even when things aren't going your way?",
    "What's the mental preparation you do specifically for facing a team with a strong reputation or a winning record?",
    "How do you mentally handle the pressure of playing for a team with high expectations?",
    "What's the mental strategy you use to stay confident when you're not getting regular playing time?",
    "How do you mentally support a teammate who is struggling with a lack of playing time?",
    "What's the mental challenge of playing multiple positions, and how do you adapt?",
    "How do you mentally prepare for the possibility of getting traded or released?",
    "What's the mental impact of playing with or against players you admire or idolize?",
    "How do you maintain your mental edge during the offseason?",
    "What's the mental transition like between the regular season and the playoffs?",
    "How do you mentally prepare for facing a pitcher who has a history of dominating your team?",
    "What's the mental approach you take when you know you're facing a must-win game?",
    "How do you mentally handle the pressure of playing in front of your family and fiends?",
    "What's the mental strategy you use to stay focused during long rain delays or other game interruptions?",
    "How do you mentally recover from a physically taxing game and prepare for the next one?",
      "What's the mental impact of playing with teammates who have significantly more or less experience than you?",
    "How do you mentally prepare for playing in different time zones and dealing with travel fatigue?",
    "What's the mental approach you take when you're facing a team that is considered a rival?",
    "How do you mentally handle the pressure of playing on a team with a long history of success or championships?",
    "What's the mental strategy you use to stay confident when you're facing a pitcher with an unorthodox pitching style?",
    "How do you mentally prepare for the possibility of playing through pain or minor injuries?",
    "What's the mental impact of playing for a manager or coaching staff with a demanding or intense personality?",
    "How do you maintain your mental focus and motivation during spring training?",
    "What's the mental strategy you use to stay confident when you're facing a hitter who has a history of hitting well against you?",
    "How do you mentally prepare for playing in games with significant playoff implications?",
    "What's the mental impact of playing on a team with a strong sense of camaraderie and team unity?",
    "How do you maintain your mental sharpness and alertness during late-inning situations?",
    "What's the mental strategy you use to stay confident when you're facing a pitcher who throws with exceptional deception?",
    "How do you mentally prepare for playing in games with unpredictable weather conditions?",
    "When you're in a slump, what's your go-to strategy for breaking out of it mentally?",
    "How do you handle the mental fatigue that can come with a long season of travel and games?",
    "What's the most valuable lesson you've learned about the mental side of baseball so far in your career?",
    "Describe a time when you felt mentally defeated on the field. What happened, and how did you eventually overcome that feeling?",
    "How important is visualization to your pre-game preparation, and what do you typically visualize?",
    "What role does self-belief play in your performance, and how do you cultivate it?",
    "How do you handle the mental challenge of facing a pitcher or hitter who has had success against you in the past?",
    "What mental adjustments do you make when playing in different game situations (e.g., close game, blowout, playoff game)?",
    "How do you use your breathing or other relaxation techniques to manage anxiety during a game?",
    "What's your approach to staying positive and optimistic even after a tough loss?",
    "How do you balance the need for individual focus with the importance of being a good teammate?",
    "What are some mental cues or triggers you use during a game to stay focused and in the present moment?",
    "How do you mentally prepare for playing in front of a large or hostile crowd?",
    "What's your philosophy on making mistakes in baseball? How do you view them?",
    "How do you mentally approach practicing skills that you find challenging or that are weaknesses?",
    "What's the biggest mental difference between performing well in practice versus performing well in a game?",
    "How do you build mental toughness over time? What specific steps do you take?",
    "What role does setting personal performance goals (beyond wins and losses) play in your mental approach?",
    "How do you handle the pressure of expectations, whether from yourself, coaches, or fans?",
    "What does mental toughness mean to you, in your own words?",
    "How do you maintain your confidence even when facing setbacks or adversity off the field?",
    "What's one mental skill you're currently trying to develop or improve?",
    "How do you use positive self-affirmations to build confidence and manage negativity?",
    "What mental strategies do you use to stay patient at the plate or on the mound?",
    "How do you mentally separate your performance in baseball from your sense of self-worth?",
    "What advice would you give to a teammate who is struggling with their confidence?",
    "How do you use the energy of your teammates and the crowd to fuel your performance?",
    "What mental tools do you use to stay present and avoid dwelling on past mistakes or future anxieties?",
    "How do you mentally prepare for facing an unfamiliar opponent?",
    "What's your process for mentally rebounding after giving up a big hit or making a crucial error?",
    "How do you maintain a competitive edge without letting it become detrimental to your mental state?",
    "What's your approach to dealing with the mental side of injuries and the recovery process?",
    "How do you stay mentally fresh and motivated throughout a demanding baseball season?",
    "What role does gratitude play in your mental approach to the game?",
    "How do you mentally handle the uncertainty and unpredictability that is inherent in baseball?",
    "What are some resources or techniques you use to train your mental game (e.g., meditation, sports psychology)?",
    "How do you communicate your mental state to your coaches or trainers if you're struggling?",
    "What does it feel like when you are truly 'in the zone' during a game?",
    "How do you use past successes to build confidence for future challenges?",
    "What's your biggest mental strength as a baseball player?",
    "What's one mental challenge you consistently face and how are you working to overcome it?",
    "How do you mentally prepare for playing in different weather conditions?",
    "What mental strategies do you use to stay focused during long periods of inactivity in a game?",
    "How do you mentally handle the scrutiny of media or social media attention?",
    "What role does trust in your training and preparation play in your mental game?",
    "How do you mentally prepare for a potential game-winning or game-losing situation?",
    "What's your approach to dealing with the mental pressure of playing for championships or in crucial games?",
    "How do you cultivate a growth mindset when it comes to the mental aspects of baseball?",
    "What mental skills do you think are most transferable to life outside of baseball?",
    "How do you stay mentally grounded and avoid getting caught up in the highs and lows of the season?",
    "What's one mental habit you're trying to develop to become a more consistent performer?",
    "How do you use setbacks as opportunities for mental growth and development?",
    "What role does self-compassion play in your ability to bounce back from mistakes?",
    "How do you mentally prepare for the possibility of failure in a high-stakes situation?",
    "What are some mental strategies you use to maintain a positive team environment?",
    "How do you communicate your confidence in your teammates' abilities?",
    "What mental skills do you think are essential for effective leadership on the field?",
    "How do you help a teammate who appears to be struggling with their mental game?",
    "What strategies do you use to build trust and rapport with your teammates?",
    "How do you approach team meetings or discussions about mental toughness?",
    "What role does vulnerability play in building a mentally strong team?",
    "How do you balance individual ambition with the team's overall goals?",
    "What mental preparations do you make for playing on the road versus playing at home?",
    "How do you stay mentally adaptable to changes in game plans or strategies?",
    "What mental techniques do you use to control your emotions during intense moments?",
    "How do you maintain your focus when facing distractions from the crowd or opposing team?",
    "What mental strategies do you use to stay confident when facing a pitcher or hitter with a dominant reputation?",
    "How do you mentally prepare for playing in different ballparks with unique dimensions or conditions?",
    "What's the biggest mental adjustment you've had to make at a higher level of competition?",
    "How do you maintain your mental sharpness and reaction time throughout a long game?",
    "What mental cues do you use to stay aggressive and assertive in your play?",
    "How do you mentally recover after a physically and emotionally draining game?",
    "What are some ways you reward yourself mentally after a successful performance or overcoming a mental challenge?",
]

# Convert the list to a numpy array
questions_array = np.array(questions)

def get_random_open_questions():
    questions_array = np.array(questions)
    num_questions_to_select = 10 
    if num_questions_to_select > len(questions_array):
        num_questions_to_select = len(questions_array)
    
    return np.random.choice(questions_array, num_questions_to_select, replace=False)